name: deploy gh-page
on:
  push:
    branches: [main]
jobs:
  build:
    name: build and deploy gh-page
    env:
      COMMIT_SECRET: ${{secrets.COMMIT_SECRET}}
      USER_NAME: adoin
      USER_EMAIL: adoin@qq.com
      PUBLISH_DIR: ./dist
      GITHUB_REPOSITORY: paint-board
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository main branch
        uses: actions/checkout@main
      - name: with node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: package install
        run: |
          npm install -g pnpm
          pnpm install
      - name: npm run build
        run: |
          pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
